services:
  - type: web
    name: my-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    rootDir: backend

  - type: static
    name: my-frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: build
    rootDir: frontend
